version: '3.8'
services:
  db:
    image: postgres:16-alpine
  
    restart: always
    environment:
      POSTGRES_USER: charry
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: database1
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      # Optional: Initialize database with custom SQL scripts
      # - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
